title: 1+MG Framework
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "Example of ELIXIR toolkit theme as a remote jekyll theme"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.23.0

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

theme_variables:
  theme_color: da366e
  topnav:
    brand_logo: assets/img/main_logo.svg
  fonts:
    - https://fonts.googleapis.com/css2?family=Fira+Sans&Open+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap
    

exclude:
  - README.md
  - .gitignore

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar1: trust_framework
      sidebar2: trust_framework2
      sidebar3: trust_framework3
      sidebar: framework
      search_exclude: false

  - 
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute
  -
    scope:
      path: "pages/data-life-cycle"
    values:
      type: data-life-cycle
  -
    scope:
      path: "pages/your-role/TEMPLATE_your_role.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/your-role"
    values:
      type: your-role
  -
    scope:
      path: "pages/your-usecase/TEMPLATE_your_usecase.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true
  -
    scope:
      path: "pages/usecases"
    values:
      type: usecases
  -
    scope:
      path: "pages/national-resources"
    values:
      type: national-resources
      datatable: true
  -
    scope:
      path: "pages/national-resources/TEMPLATE_resources.md"
      type: "pages"
    values:
      sitemap: false
      search_exclude: true
      no_robots: true

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
